Query:
    type: object
    config:
        fields:
            users:
                type: "[User!]"
                resolve: "@=service('graphql.query_resolver').users()"
            me:
                type: "User!"
                resolve: "@=service('graphql.query_resolver').me()"
            tasks:
                type: "[Task!]"
                resolve: "@=service('graphql.query_resolver').tasks()"
            tasksByUser:
                type: "[Task!]"
                args:
                    userId:
                        type: "Int!"
                resolve: "@=service('graphql.query_resolver').tasksByUser(args['userId'])"
