Query:
    type: object
    config:
        fields:
            users:
                type: "[User!]!"
                resolve: "@=service('graphql.query_resolver').users()"
            me:
                type: "User!"
                resolve: "@=service('graphql.query_resolver').me()"
