Query:
    type: object
    config:
        fields:
            users:
                type: "[User!]"
                resolve: "@=service('graphql.query_resolver').users()"
            me:
                type: "User!"
                resolve: "@=service('graphql.query_resolver').me()"
            tasks:
                type: "[Task!]"
                resolve: "@=service('graphql.query_resolver').tasks()"
            tasksByUser:
                type: "[Task!]"
                args:
                    userId:
                        type: "Int!"
                resolve: "@=service('graphql.query_resolver').tasksByUser(args['userId'])"
            events:
                type: "[Event!]"
                resolve: "@=service('graphql.query_resolver').events()"
            eventsForTask:
                type: "[Event!]"
                args:
                    eventType:
                        type: "String!"
                    aggregateId:
                        type: "Int!"
                resolve: "@=service('graphql.query_resolver').eventsForTask(args)"
