User:
    type: object
    config:
        description: "User representation"
        fields:
            id:
                type: "ID!"
            name:
                type: "String!"
            username:
                type: "String!"
            email:
                type: "String!"
